services:
  news:
    image: news
    depends_on:
      - pg
      - user
      - jaeger
    ports:
      - "8080:8100"
    environment:
      PG_CONN: postgres://postgres@pg?password=dev&sslmode=disable
      USER_SRV: http://user:8091
      JAEGER_AGENT_HOST: jaeger
  user:
    image: user
    depends_on: 
      - jaeger
      - pg
    ports:
      - "8091:8091"
    environment:
      PG_CONN: postgres://postgres@pg?password=dev&sslmode=disable
      PRIVATE_KEY: eZhYkbiHIeA6TiVJoqa2seyYd8GonwsvuEfgz0DezYXBB1mxlKbFrMO+Cd5AooKDP9ORAuXNSP4Rrt1RDr6SKw==
      PUBLIC_KEY: wQdZsZSmxazDvgneQKKCgz/TkQLlzUj+Ea7dUQ6+kis=
      JAEGER_AGENT_HOST: jaeger
  pg:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: dev
  prometheus:
    image: prom/prometheus:latest
    ports:
    - "9090:9090"
    volumes:
      - ./dockerfiles/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
    - "16686:16686"
